name: ia_web_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.5
  uuid: ^4.5.1
  file_picker: ^6.1.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  flutter_quill: 11.4.0
  flutter_quill_extensions:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      path: flutter_quill_extensions
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/flags/
    - assets/images/socialmedia/
    - assets/images/icons/